empty_dash_retention_in_days: 2
deploy_path: "superset_objects"
turn_chart_description: True
delete_old_object_versions: True
remove_unassociated_charts: False
min_level_deployment_object_class: datasets