_deploy_dataset_name: birth_names
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 7ec75d28-760b-4189-899a-7d9e3aadee07
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50
  time_range: '100 years ago : now'
  timeseries_limit_metric: sum__num
  viz_type: table
query_context: null
slice_name: Girls
uuid: d016f304-b3b4-4bde-a4d3-a1f55b8ca227
version: 1.0.0
viz_type: table
