_deploy_dataset_name: members_channels_2
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 3d9c0054-b31b-4102-92de-b1ef9f9e5e77
description: null
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 57__table
  groupby:
  - channel_name
  label_colors: {}
  metrics:
  - count
  number_format: SMART_NUMBER
  queryFields:
    groupby: groupby
    metrics: metrics
  row_limit: null
  slice_id: 2396
  time_range: No filter
  treemap_ratio: 1.618033988749895
  url_params: {}
  viz_type: treemap
query_context: null
slice_name: Members per Channel
uuid: d44e416d-1647-44e4-b442-6da34b44adc4
version: 1.0.0
viz_type: treemap
