_deploy_dataset_name: wb_health_population
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: c9a144d9-72f2-491a-85d2-b4517e0b20dc
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: table
query_context: null
slice_name: Most Populated Countries
uuid: 08871493-a5f9-43a3-84f3-71ca7afd0753
version: 1.0.0
viz_type: table
