_deploy_dataset_name: birth_names
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 7ec75d28-760b-4189-899a-7d9e3aadee07
description: null
params:
  compare_lag: '5'
  compare_suffix: over 5Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__num
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: big_number
query_context: null
slice_name: Participants
uuid: 688afb19-9fd0-49a4-b9cf-d7545ea33766
version: 1.0.0
viz_type: big_number
