_deploy_dataset_name: wb_health_population
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: c9a144d9-72f2-491a-85d2-b4517e0b20dc
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  date_filter: false
  entity: country_code
  filter_configs:
  - asc: false
    clearable: true
    column: region
    key: 2s98dfu
    metric: sum__SP_POP_TOTL
    multiple: false
  - asc: false
    clearable: true
    column: country_name
    key: li3j2lk
    metric: sum__SP_POP_TOTL
    multiple: true
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  row_limit: 50000
  show_bubbles: true
  since: '2014-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: filter_box
query_context: null
slice_name: Region Filter
uuid: da85f29a-0c9a-4b26-9174-201f763c1e1a
version: 1.0.0
viz_type: filter_box
