_deploy_dataset_name: birth_names
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 7ec75d28-760b-4189-899a-7d9e3aadee07
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  comparison_type: values
  granularity_sqla: ds
  groupby:
  - name
  limit: 10
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  stacked_style: expand
  time_grain_sqla: P1D
  time_range: '100 years ago : now'
  viz_type: area
  x_axis_forma: smart_date
query_context: null
slice_name: Top 10 Girl Name Share
uuid: dcecbf15-3546-4d11-83dd-83e7237aefe4
version: 1.0.0
viz_type: area
