_deploy_dataset_name: birth_names
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 7ec75d28-760b-4189-899a-7d9e3aadee07
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  rich_tooltip: true
  row_limit: 50000
  show_legend: true
  time_range: '100 years ago : now'
  viz_type: line
query_context: null
slice_name: Trends
uuid: d8e21bd2-336d-400d-8cc8-c307ecffaa02
version: 1.0.0
viz_type: line
