_deploy_dataset_name: wb_health_population
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: c9a144d9-72f2-491a-85d2-b4517e0b20dc
description: null
params:
  compare_lag: '10'
  compare_suffix: over 10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2000'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: big_number
query_context: null
slice_name: World's Population
uuid: ad16f7ec-5aed-46d3-bd1f-36d0fd959af1
version: 1.0.0
viz_type: big_number
